# Generated by Django 5.2.15 on 2026-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingcampaign',
            name='current_milestone_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Set 0 before construction starts, 1 for the first milestone, 2 for the second, and so on. The public construction progress updates automatically.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scripture_reference_en',
            field=models.CharField(default='Micah 4:5', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scripture_reference_ro',
            field=models.CharField(blank=True, default='Mica 4:5', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scripture_text_en',
            field=models.TextField(default='For all people will walk every one in the name of his god, and we will walk in the name of the Lord our God for ever and ever.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scripture_text_ro',
            field=models.TextField(blank=True, default='Toate popoarele umblă fiecare în numele dumnezeului său, iar noi vom umbla în Numele Domnului Dumnezeului nostru, totdeauna și în veci.'),
        ),
    ]
