# Generated by Django 5.2.15 on 2026-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_fundraisingcampaign_current_milestone_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='scripture_text_ro',
            field=models.TextField(blank=True, default='„Pe când toate popoarele umblă fiecare în numele dumnezeului său, noi vom umbla în Numele Domnului, Dumnezeului nostru, totdeauna şi în veci de veci!”'),
        ),
    ]
