# Generated by Django 5.2.15 on 2026-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_sitesettings_scripture_text_ro'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='constructionupdate',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='donationmethod',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide this photo without removing it from the event.', verbose_name='Show in slideshow'),
        ),
        migrations.AddField(
            model_name='fundraisingcampaign',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='givingtier',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide the entire page without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide it without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Turn this off to hide this service time without deleting it.', verbose_name='Show on website'),
        ),
    ]
