# Generated by Django 5.2.15 on 2026-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_announcement_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_building_fundraising',
            field=models.BooleanField(default=True, verbose_name='Building fundraising progress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_building_giving_tiers',
            field=models.BooleanField(default=True, verbose_name='Building giving tiers'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_building_milestones',
            field=models.BooleanField(default=True, verbose_name='Building construction timeline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_building_updates',
            field=models.BooleanField(default=True, verbose_name='Building photo updates'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_charity_donations',
            field=models.BooleanField(default=True, verbose_name='Charity donation section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_contact_details',
            field=models.BooleanField(default=True, verbose_name='Contact page details'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_contact_forms',
            field=models.BooleanField(default=True, verbose_name='Contact and prayer forms'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_events_listing',
            field=models.BooleanField(default=True, verbose_name='Events listing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Website footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_contact_details',
            field=models.BooleanField(default=True, verbose_name='Homepage contact details'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_fundraising',
            field=models.BooleanField(default=True, verbose_name='Homepage fundraising progress'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_latest_update',
            field=models.BooleanField(default=True, verbose_name='Homepage latest building update'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_newsletter',
            field=models.BooleanField(default=True, verbose_name='Homepage newsletter signup'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_scripture',
            field=models.BooleanField(default=True, verbose_name='Homepage scripture'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_service_schedule',
            field=models.BooleanField(default=True, verbose_name='Homepage service schedule'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_team',
            field=models.BooleanField(default=True, verbose_name='Homepage team section'),
        ),
    ]
