# Generated by Django 5.2.15 on 2026-06-08 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_page_blocks(apps, schema_editor):
    Page = apps.get_model("church", "Page")
    PageBlock = apps.get_model("church", "PageBlock")
    SiteSettings = apps.get_model("church", "SiteSettings")
    from church.page_blocks import PAGE_BLOCK_DEFAULTS

    Page.objects.update_or_create(
        slug="member-updates",
        defaults={
            "nav_title_en": "Member Updates",
            "nav_title_ro": "Actualiz\u0103ri pentru membri",
            "hero_title_en": "Member Updates",
            "hero_title_ro": "Actualiz\u0103ri pentru membri",
            "hero_subtitle_en": "Private announcements and updates for signed-in users",
            "hero_subtitle_ro": "Anun\u021buri \u015fi nout\u0103\u021bi private pentru utilizatorii autentifica\u021bi",
            "meta_title_en": "Member Updates - Mount Zion Church",
            "meta_title_ro": "Actualiz\u0103ri pentru membri - Biserica Mount Zion",
            "meta_description_en": "Private Mount Zion announcements and building updates for signed-in members.",
            "meta_description_ro": "Anun\u021buri \u015fi actualiz\u0103ri private Mount Zion pentru membrii autentifica\u021bi.",
            "navigation_order": 80,
            "show_in_navigation": False,
        },
    )

    site_settings = SiteSettings.objects.filter(pk=1).first()
    visibility_fields = {
        ("home", "construction_popup"): "show_construction_popup",
        ("home", "scripture"): "show_home_scripture",
        ("home", "service_schedule"): "show_home_service_schedule",
        ("home", "fundraising"): "show_home_fundraising",
        ("home", "latest_update"): "show_home_latest_update",
        ("home", "team"): "show_home_team",
        ("home", "newsletter"): "show_home_newsletter",
        ("home", "home_address"): "show_home_contact_details",
        ("home", "home_email"): "show_home_contact_details",
        ("home", "home_phone"): "show_home_contact_details",
        ("charity", "donations"): "show_charity_donations",
        ("building", "fundraising"): "show_building_fundraising",
        ("building", "giving_tiers"): "show_building_giving_tiers",
        ("building", "milestones"): "show_building_milestones",
        ("building", "updates"): "show_building_updates",
        ("events", "events_listing"): "show_events_listing",
        ("contact", "contact_address"): "show_contact_details",
        ("contact", "contact_email"): "show_contact_details",
        ("contact", "contact_phone"): "show_contact_details",
        ("contact", "contact_form"): "show_contact_forms",
        ("contact", "prayer_form"): "show_contact_forms",
    }

    for page_slug, blocks in PAGE_BLOCK_DEFAULTS.items():
        page = Page.objects.filter(slug=page_slug).first()
        if not page:
            continue
        for block_defaults in blocks:
            defaults = block_defaults.copy()
            key = defaults.pop("key")
            visibility_field = visibility_fields.get((page_slug, key))
            if site_settings and visibility_field:
                defaults["is_visible"] = getattr(site_settings, visibility_field)
            if site_settings and page_slug == "home" and key == "construction_popup":
                defaults.update(
                    {
                        "title_en": site_settings.construction_popup_title_en,
                        "title_ro": site_settings.construction_popup_title_ro,
                        "body_en": site_settings.construction_popup_body_en,
                        "body_ro": site_settings.construction_popup_body_ro,
                        "button_text_en": site_settings.construction_popup_button_en,
                        "button_text_ro": site_settings.construction_popup_button_ro,
                        "button_url": site_settings.current_church_url,
                    }
                )
            if site_settings and page_slug == "home" and key == "scripture":
                defaults.update(
                    {
                        "title_en": site_settings.scripture_reference_en,
                        "title_ro": site_settings.scripture_reference_ro,
                        "body_en": site_settings.scripture_text_en,
                        "body_ro": site_settings.scripture_text_ro,
                    }
                )
            PageBlock.objects.update_or_create(
                page=page,
                key=key,
                defaults=defaults,
            )


def remove_seeded_page_blocks(apps, schema_editor):
    Page = apps.get_model("church", "Page")
    PageBlock = apps.get_model("church", "PageBlock")
    PageBlock.objects.all().delete()
    Page.objects.filter(slug="member-updates").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_sitesettings_show_building_fundraising_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Show event description'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_gallery',
            field=models.BooleanField(default=True, verbose_name='Show event slideshow'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_hero',
            field=models.BooleanField(default=True, verbose_name='Show event hero'),
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('title_ro', models.CharField(blank=True, max_length=180)),
                ('subtitle_en', models.CharField(blank=True, max_length=180)),
                ('subtitle_ro', models.CharField(blank=True, max_length=180)),
                ('body_en', models.TextField(blank=True)),
                ('body_ro', models.TextField(blank=True)),
                ('image_static', models.CharField(blank=True, max_length=255)),
                ('button_text_en', models.CharField(blank=True, max_length=80)),
                ('button_text_ro', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Turn this off to hide this built-in page section without deleting it.', verbose_name='Show on website')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.imageasset')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='church.page')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Built-in page section',
                'verbose_name_plural': 'Built-in page sections',
                'ordering': ['page', 'order', 'label'],
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.RunPython(seed_page_blocks, remove_seeded_page_blocks),
    ]
