# Generated by Django 5.2.15 on 2026-06-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_seed_home_construction_popup_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages_replied_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Write the email reply here, then use the send button below.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_subject',
            field=models.CharField(blank=True, help_text='The subject line that will be sent to the visitor.', max_length=180),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='replied_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests_replied_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Write the email reply here, then use the send button below.'),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reply_subject',
            field=models.CharField(blank=True, help_text='The subject line that will be sent to the visitor.', max_length=180),
        ),
    ]
