from django import template
from django.templatetags.static import static
from django.utils.translation import get_language


register = template.Library()


UI_TEXT = {
    "en": {
        "home": "Home",
        "services": "Services",
        "about": "About",
        "charity": "Charity",
        "building_fund": "Building Fund",
        "events": "Events",
        "contact": "Contact",
        "members": "Members",
        "login": "Login",
        "logout": "Logout",
        "menu": "Menu",
        "view": "View",
        "accept": "Accept",
        "closed": "Closed",
        "church_opening_hours": "Church Opening Hours",
        "raised": "raised",
        "goal": "goal",
        "latest_update": "Latest update",
        "meet_team": "Meet Our Team",
        "subscribe_title": "Subscribe for church updates",
        "subscribe_intro": "Choose the announcements you want: fundraising, youth, prayer, services, and building updates.",
        "name": "Name",
        "email": "Email",
        "language": "Language",
        "choose_updates": "Choose updates",
        "subscribe": "Subscribe",
        "address": "Address",
        "phone": "Phone",
        "support_mission": "Support Our Mission",
        "donation_soon": "Donation details will be added soon.",
        "giving_tiers": "Giving Tiers",
        "construction_timeline": "Construction Timeline",
        "construction_progress": "Construction progress",
        "step": "Step",
        "of": "of",
        "not_started": "Not started",
        "target": "Target",
        "photo_updates": "Photo Updates",
        "building_soon": "Building fund details will be added soon.",
        "give": "Give",
        "events_soon": "Events and church activity updates will be added soon.",
        "send_message": "Send a Message",
        "send_message_button": "Send Message",
        "prayer_request": "Prayer Request",
        "send_prayer_button": "Send Prayer Request",
        "member_updates": "Member Updates",
        "member_updates_subtitle": "Private announcements and updates for signed-in users",
        "announcements": "Announcements",
        "no_member_announcements": "No member announcements yet.",
        "building_updates": "Building Updates",
        "no_building_updates": "No building updates yet.",
        "unsubscribed_title": "You have been unsubscribed",
        "unsubscribed_body": "will no longer receive newsletter emails.",
        "return_home": "Return Home",
        "member_login": "Member Login",
        "member_login_intro": "Sign in to see member-only announcements and updates.",
        "forgot_password": "Forgot password?",
        "create_account_link": "Create account",
        "create_member_account": "Create Member Account",
        "create_member_intro": "Create an account to see updates that are shared only with logged-in users.",
        "create_account_button": "Create Account",
        "already_have_account": "Already have an account?",
        "admin_login": "Website Admin Login",
        "admin_login_intro": "This private page is only for approved Mount Zion website administrators.",
        "login_admin": "Login to Admin",
        "create_admin": "Create Admin Account",
        "create_admin_intro": "This private signup link can be used once before it expires.",
        "create_admin_button": "Create Admin",
        "reset_password": "Reset Password",
        "reset_password_intro": "Enter your email address and we will send a reset link.",
        "send_reset_link": "Send Reset Link",
        "check_email": "Check Your Email",
        "check_email_intro": "If an account exists with that address, a password reset link has been sent.",
        "choose_new_password": "Choose New Password",
        "update_password": "Update Password",
        "invalid_reset_link": "This password reset link is invalid or has expired.",
        "request_new_link": "Request New Link",
        "password_updated": "Password Updated",
        "password_updated_intro": "Your password has been changed. You can now log in.",
        "admin_brand_title": "Mount Zion Admin",
        "admin_brand_subtitle": "Church website workspace",
        "admin_signed_in_as": "Signed in as",
        "admin_view_website": "View website",
        "admin_password": "Password",
        "admin_logout": "Log out",
        "admin_private_administration": "Private administration",
        "admin_welcome_back": "Welcome back",
        "admin_signin_intro": "Sign in to manage the Mount Zion website.",
        "admin_sign_in": "Sign in",
        "admin_check_highlighted": "Please check the highlighted field and try again.",
        "admin_no_access_prefix": "You are signed in as",
        "admin_no_access_suffix": "but this account cannot access the admin area.",
        "admin_dashboard_kicker": "Mount Zion website",
        "admin_dashboard_welcome": "Good to see you,",
        "admin_dashboard_intro": "Manage the website, church communications, fundraising updates, and messages from one place.",
        "admin_view_live_website": "View live website",
        "admin_subscribers": "Subscribers",
        "admin_active_newsletter_contacts": "Active newsletter contacts",
        "admin_new_messages": "New messages",
        "admin_waiting_for_review": "Waiting for review",
        "admin_prayer_requests": "Prayer requests",
        "admin_new_requests_received": "New requests received",
        "admin_building_fund": "Building fund",
        "admin_website_content": "Website content",
        "admin_website_content_intro": "Keep the public pages and visual content up to date.",
        "admin_pages_sections": "Pages and sections",
        "admin_pages_sections_desc": "Edit headings, Romanian translations, page sections, and SEO text.",
        "admin_image_library": "Image library",
        "admin_image_library_desc": "Upload, organize, and reuse optimized photos across the website.",
        "admin_service_schedule": "Service schedule",
        "admin_service_schedule_desc": "Update weekly services, opening times, and closed days.",
        "admin_site_settings": "Site settings",
        "admin_site_settings_desc": "Manage contact details, homepage scripture, footer, and popup.",
        "admin_communications": "Communications",
        "admin_communications_intro": "Publish updates and stay connected with the church community.",
        "admin_announcements_desc": "Create urgent banners and public or members-only notices.",
        "admin_events_galleries": "Events and galleries",
        "admin_events_galleries_desc": "Share church activities, descriptions, photos, and slideshows.",
        "admin_newsletter_composer": "Newsletter composer",
        "admin_newsletter_composer_desc": "Prepare bilingual emails, save drafts, and send by category.",
        "admin_subscriber_list": "Subscriber list",
        "admin_subscriber_list_desc": "Review active subscribers, preferences, and consent status.",
        "admin_fundraising_building": "Fundraising and building",
        "admin_fundraising_building_intro": "Keep donors informed and the campaign progress accurate.",
        "admin_building_campaign": "Building campaign",
        "admin_building_campaign_desc": "Update totals, construction stage, giving tiers, and photo updates.",
        "admin_donation_methods": "Donation methods",
        "admin_donation_methods_desc": "Manage bank details, QR codes, and online giving links.",
        "admin_quick_actions": "Quick actions",
        "admin_quick_actions_intro": "Common tasks, one click away.",
        "admin_edit_homepage": "Edit homepage",
        "admin_new_announcement": "New announcement",
        "admin_add_event": "Add an event",
        "admin_write_newsletter": "Write newsletter",
        "admin_upload_image": "Upload an image",
        "admin_needs_attention": "Needs attention",
        "admin_needs_attention_intro": "Items still waiting on the team.",
        "admin_new_message_label": "new messages",
        "admin_new_prayer_label": "new prayer requests",
        "admin_draft_announcement_label": "draft announcements",
        "admin_draft_event_label": "draft events",
        "admin_draft_newsletter_label": "draft newsletters",
        "admin_recent_activity": "Recent activity",
        "admin_recent_activity_intro": "Your latest admin changes.",
        "admin_empty_recent": "Your recent changes will appear here.",
        "admin_ago": "ago",
        "admin_navigation": "Admin navigation",
        "admin_filter_menu": "Filter menu...",
        "admin_filter_navigation": "Filter navigation items",
        "admin_overview": "Overview",
        "admin_dashboard": "Dashboard",
        "admin_website": "Website",
        "admin_church_team": "Church team",
        "admin_newsletters": "Newsletters",
        "admin_fundraising": "Fundraising",
        "admin_inbox": "Inbox",
        "admin_contact_messages": "Contact messages",
        "admin_people_access": "People and access",
        "admin_users": "Users",
        "admin_admin_invites": "Admin invites",
        "admin_confirm_send_newsletter": "Send the selected newsletter now? This will email matching subscribers.",
        "admin_shown_on_website": "Shown on website",
        "admin_hidden_from_website": "Hidden from website",
        "admin_shown_on_website_title": "Shown on website. Switch off to hide.",
        "admin_hidden_from_website_title": "Hidden from website. Switch on to show.",
        "admin_visible": "Visible",
        "admin_hidden": "Hidden",
        "admin_email_reply": "Email reply",
        "admin_reply_will_send_to": "The reply will be sent to",
        "admin_from_church_mailbox": "from the church mailbox.",
        "admin_no_email_reply": "No email address was provided, so this request cannot receive an email reply.",
        "admin_save_send_email_reply": "Save and send email reply",
        "admin_confirm_send_email_reply": "Send this email reply now?",
    },
    "ro": {
        "home": "Acasă",
        "services": "Servicii",
        "about": "Despre noi",
        "charity": "Caritate",
        "building_fund": "Fondul de construcție",
        "events": "Evenimente",
        "contact": "Contact",
        "members": "Membri",
        "login": "Autentificare",
        "logout": "Ieșire",
        "menu": "Meniu",
        "view": "Vezi",
        "accept": "Accept",
        "closed": "Închis",
        "church_opening_hours": "Programul bisericii",
        "raised": "strânși",
        "goal": "obiectiv",
        "latest_update": "Ultima actualizare",
        "meet_team": "Echipa noastră",
        "subscribe_title": "Abonează-te la noutățile bisericii",
        "subscribe_intro": "Alege anunțurile dorite: strângere de fonduri, tineret, rugăciune, servicii și actualizări despre construcție.",
        "name": "Nume",
        "email": "Email",
        "language": "Limbă",
        "choose_updates": "Alege noutățile",
        "subscribe": "Abonează-te",
        "address": "Adresă",
        "phone": "Telefon",
        "support_mission": "Susține misiunea noastră",
        "donation_soon": "Detaliile pentru donații vor fi adăugate în curând.",
        "giving_tiers": "Niveluri de donație",
        "construction_timeline": "Etapele construcției",
        "construction_progress": "Progresul construcției",
        "step": "Etapa",
        "of": "din",
        "not_started": "Construcția nu a început",
        "target": "Țintă",
        "photo_updates": "Actualizări foto",
        "building_soon": "Detaliile fondului de construcție vor fi adăugate în curând.",
        "give": "Donează",
        "events_soon": "Evenimentele și activitățile bisericii vor fi adăugate în curând.",
        "send_message": "Trimite un mesaj",
        "send_message_button": "Trimite mesajul",
        "prayer_request": "Cerere de rugăciune",
        "send_prayer_button": "Trimite cererea",
        "member_updates": "Actualizări pentru membri",
        "member_updates_subtitle": "Anunțuri și noutăți private pentru utilizatorii autentificați",
        "announcements": "Anunțuri",
        "no_member_announcements": "Nu există încă anunțuri pentru membri.",
        "building_updates": "Actualizări despre construcție",
        "no_building_updates": "Nu există încă actualizări despre construcție.",
        "unsubscribed_title": "Ai fost dezabonat",
        "unsubscribed_body": "nu va mai primi emailuri cu noutăți.",
        "return_home": "Înapoi acasă",
        "member_login": "Autentificare membri",
        "member_login_intro": "Autentifică-te pentru a vedea anunțurile și actualizările doar pentru membri.",
        "forgot_password": "Ai uitat parola?",
        "create_account_link": "Creează cont",
        "create_member_account": "Creează cont de membru",
        "create_member_intro": "Creează un cont pentru a vedea actualizările disponibile doar utilizatorilor autentificați.",
        "create_account_button": "Creează cont",
        "already_have_account": "Ai deja cont?",
        "admin_login": "Autentificare administratori",
        "admin_login_intro": "Această pagină privată este doar pentru administratorii aprobați ai site-ului Mount Zion.",
        "login_admin": "Intră în administrare",
        "create_admin": "Creează cont de administrator",
        "create_admin_intro": "Acest link privat poate fi folosit o singură dată înainte să expire.",
        "create_admin_button": "Creează administrator",
        "reset_password": "Resetare parolă",
        "reset_password_intro": "Introdu adresa de email și îți vom trimite un link de resetare.",
        "send_reset_link": "Trimite linkul",
        "check_email": "Verifică emailul",
        "check_email_intro": "Dacă există un cont cu această adresă, a fost trimis un link de resetare.",
        "choose_new_password": "Alege o parolă nouă",
        "update_password": "Actualizează parola",
        "invalid_reset_link": "Acest link de resetare este invalid sau a expirat.",
        "request_new_link": "Cere un link nou",
        "password_updated": "Parola a fost actualizată",
        "password_updated_intro": "Parola ta a fost schimbată. Acum te poți autentifica.",
        "admin_brand_title": "Administrare Mount Zion",
        "admin_brand_subtitle": "Spațiul de lucru al site-ului",
        "admin_signed_in_as": "Autentificat ca",
        "admin_view_website": "Vezi site-ul",
        "admin_password": "Parolă",
        "admin_logout": "Ieșire",
        "admin_private_administration": "Administrare privată",
        "admin_welcome_back": "Bine ai revenit",
        "admin_signin_intro": "Autentifică-te pentru a administra site-ul Mount Zion.",
        "admin_sign_in": "Autentificare",
        "admin_check_highlighted": "Verifică câmpul evidențiat și încearcă din nou.",
        "admin_no_access_prefix": "Ești autentificat ca",
        "admin_no_access_suffix": "dar acest cont nu poate accesa zona de administrare.",
        "admin_dashboard_kicker": "Site-ul Mount Zion",
        "admin_dashboard_welcome": "Mă bucur să te revăd,",
        "admin_dashboard_intro": "Administrează site-ul, comunicările bisericii, actualizările de strângere de fonduri și mesajele dintr-un singur loc.",
        "admin_view_live_website": "Vezi site-ul public",
        "admin_subscribers": "Abonați",
        "admin_active_newsletter_contacts": "Contacte active pentru newsletter",
        "admin_new_messages": "Mesaje noi",
        "admin_waiting_for_review": "Așteaptă verificare",
        "admin_prayer_requests": "Cereri de rugăciune",
        "admin_new_requests_received": "Cereri noi primite",
        "admin_building_fund": "Fondul de construcție",
        "admin_website_content": "Conținutul site-ului",
        "admin_website_content_intro": "Menține paginile publice și conținutul vizual actualizate.",
        "admin_pages_sections": "Pagini și secțiuni",
        "admin_pages_sections_desc": "Editează titluri, traduceri în română, secțiuni și texte SEO.",
        "admin_image_library": "Bibliotecă imagini",
        "admin_image_library_desc": "Încarcă, organizează și refolosește fotografii optimizate pe site.",
        "admin_service_schedule": "Program servicii",
        "admin_service_schedule_desc": "Actualizează serviciile săptămânale, orele și zilele închise.",
        "admin_site_settings": "Setări site",
        "admin_site_settings_desc": "Administrează datele de contact, versetul de pe homepage, footerul și popup-ul.",
        "admin_communications": "Comunicări",
        "admin_communications_intro": "Publică noutăți și păstrează legătura cu comunitatea bisericii.",
        "admin_announcements_desc": "Creează bannere urgente și anunțuri publice sau doar pentru membri.",
        "admin_events_galleries": "Evenimente și galerii",
        "admin_events_galleries_desc": "Publică activități ale bisericii, descrieri, fotografii și slideshow-uri.",
        "admin_newsletter_composer": "Editor newsletter",
        "admin_newsletter_composer_desc": "Pregătește emailuri bilingve, salvează drafturi și trimite pe categorii.",
        "admin_subscriber_list": "Lista abonaților",
        "admin_subscriber_list_desc": "Verifică abonații activi, preferințele și consimțământul.",
        "admin_fundraising_building": "Strângere de fonduri și construcție",
        "admin_fundraising_building_intro": "Ține donatorii informați și progresul campaniei corect.",
        "admin_building_campaign": "Campania de construcție",
        "admin_building_campaign_desc": "Actualizează totalurile, etapa construcției, nivelurile de donație și pozele.",
        "admin_donation_methods": "Metode de donație",
        "admin_donation_methods_desc": "Administrează detaliile bancare, codurile QR și linkurile de donație online.",
        "admin_quick_actions": "Acțiuni rapide",
        "admin_quick_actions_intro": "Sarcini comune, la un click distanță.",
        "admin_edit_homepage": "Editează homepage-ul",
        "admin_new_announcement": "Anunț nou",
        "admin_add_event": "Adaugă eveniment",
        "admin_write_newsletter": "Scrie newsletter",
        "admin_upload_image": "Încarcă imagine",
        "admin_needs_attention": "Necesită atenție",
        "admin_needs_attention_intro": "Elemente care așteaptă echipa.",
        "admin_new_message_label": "mesaje noi",
        "admin_new_prayer_label": "cereri noi de rugăciune",
        "admin_draft_announcement_label": "anunțuri draft",
        "admin_draft_event_label": "evenimente draft",
        "admin_draft_newsletter_label": "newslettere draft",
        "admin_recent_activity": "Activitate recentă",
        "admin_recent_activity_intro": "Ultimele modificări din administrare.",
        "admin_empty_recent": "Modificările recente vor apărea aici.",
        "admin_ago": "în urmă",
        "admin_navigation": "Navigare administrare",
        "admin_filter_menu": "Filtrează meniul...",
        "admin_filter_navigation": "Filtrează elementele de navigare",
        "admin_overview": "Privire de ansamblu",
        "admin_dashboard": "Panou principal",
        "admin_website": "Site",
        "admin_church_team": "Echipa bisericii",
        "admin_newsletters": "Newslettere",
        "admin_fundraising": "Strângere de fonduri",
        "admin_inbox": "Mesaje primite",
        "admin_contact_messages": "Mesaje de contact",
        "admin_people_access": "Persoane și acces",
        "admin_users": "Utilizatori",
        "admin_admin_invites": "Invitații administratori",
        "admin_confirm_send_newsletter": "Trimiți acum newsletterul selectat? Emailul va fi trimis abonaților potriviți.",
        "admin_shown_on_website": "Afișat pe site",
        "admin_hidden_from_website": "Ascuns de pe site",
        "admin_shown_on_website_title": "Afișat pe site. Dezactivează pentru a ascunde.",
        "admin_hidden_from_website_title": "Ascuns de pe site. Activează pentru a afișa.",
        "admin_visible": "Vizibil",
        "admin_hidden": "Ascuns",
        "admin_email_reply": "Răspuns prin email",
        "admin_reply_will_send_to": "Răspunsul va fi trimis către",
        "admin_from_church_mailbox": "din căsuța de email a bisericii.",
        "admin_no_email_reply": "Nu a fost furnizată nicio adresă de email, deci această cerere nu poate primi răspuns prin email.",
        "admin_save_send_email_reply": "Salvează și trimite răspunsul",
        "admin_confirm_send_email_reply": "Trimiți acum acest răspuns prin email?",
    },
}


def active_language():
    return (get_language() or "en").split("-")[0]


@register.filter
def tr(obj, field_name):
    language = active_language()
    translated = getattr(obj, f"{field_name}_{language}", "")
    english = getattr(obj, f"{field_name}_en", "")
    fallback = getattr(obj, field_name, "")
    return translated or english or fallback


@register.simple_tag
def ui(key):
    language = active_language()
    return UI_TEXT.get(language, UI_TEXT["en"]).get(key, UI_TEXT["en"].get(key, key))


@register.simple_tag
def image_source(asset=None, static_path=""):
    if asset and getattr(asset, "image", None):
        return asset.image.url
    if static_path:
        return static(static_path)
    return ""


@register.filter
def split_lines(value):
    if not value:
        return []
    return [line.strip() for line in str(value).splitlines() if line.strip()]


@register.filter
def currency(value):
    if value is None:
        return "€0"
    return f"€{value:,.0f}"


@register.filter
def get_item(mapping, key):
    if not mapping:
        return None
    return mapping.get(key)
